### ISSUE TITLE
integraton with gulp

### ISSUE THREAD

**Issue by Metis77** [jxnblk/react-static-site-boilerplate#3]
for my work I’d love to use this together with gulp as i use several other gulp tasks.
It works fine, except the webpack-dev-server inside gulp.

Is there a known issue?

**Comment by jxnblk** [comment]
I've not tried using webpack with gulp. My best guess is to search for a tutorial or boilerplate that has the two set up together. For my own purposes, webpack has essentially replaced everything that I used to use gulp for.
