### ISSUE TITLE
Way to not include CSS as inline in every build .html file

### ISSUE THREAD

**Issue by sahanDissanayake** [jxnblk/react-static-site-boilerplate#7]
Maybe not an issue but would love to have some description on how to do this on README

**Comment by jxnblk** [comment]
Not sure why you wouldn't want styles, but you'd just need to remove these lines:
- https://github.com/jxnblk/react-static-site-boilerplate/blob/master/components/Root.jsx#L7
- https://github.com/jxnblk/react-static-site-boilerplate/blob/master/components/Root.jsx#L23
