### ISSUE TITLE
path for assets in static pages

### ISSUE THREAD

**Issue by jacobhamblin** [jxnblk/react-static-site-boilerplate#8]
Serve up the repository and visit the static about page and you'll see that it fails to load bundle.js, as it expects bundle.js to be in the current directory. How hard would it be to enable client-side js from any page on the site? I have image files and other information that is properly found by the generated index.html on the root level, but html files in subdirectories expect to find them all in their own directories.

**Comment by jacobhamblin** [comment]
The issue is solved by astraw's commit, it's the relative vs absolute path thing (adding a / before the filenames). The change in the jsx file hasn't been applied through the npm scripts, so I thought I'd apply it for you. However, if I serve up the folder using another standard service like python SimpleHTTPServer, I get the following error:

```
Uncaught Error: Invariant Violation: You're trying to render a component to the document using server rendering but the checksum was invalid. This usually means you rendered a different component type or props on the client from the one on the server, or your render() methods are impure. React cannot handle this case due to cross-browser quirks by rendering at the document root. You should look for environment dependent code in your components and ensure the props are the same client and server side:
 (client) <noscript data-reacti
 (server) <html data-reactid=".
```

Do you know what the problem is? I'm getting the same error in my own project.

**Comment by hew** [comment]
I encountered this too. I think from what I can remember, I had to change the routes too. If you haven't, try that. 

[See example](https://github.com/oompt/react-static-boilerplate-ES6/blob/master/components/Header.jsx#L21)
